spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
  datasource:
    hikari:
      pool-name: marketplace-pool
    url: jdbc:oracle:thin:@//10.0.32.32:1521/umico
    username: umico
    password: 7?-+sfVndfe2L=4\Nk3B
  cloud:
    function:
      definition: checkFraud;checkFraudResult;scoringResult;verificationResult;prePurchase;prePurchaseResult
    stream:
      binders:
        kafka-bpm:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: 10.0.81.75:9094
        kafka-mp:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: localhost:9092
            auto-create-topics: true
            auto-add-partitions: true
            min-partition-count: 1
      bindings:
        scoringResult-in-0:
          binder: kafka-bpm
          contentType: application/json
          destination: bpm-market-place-online-state
          group: marketplace-bpm-online-state-local
        checkFraudResult-in-0:
          binder: kafka-mp
          contentType: application/json
          group: marketplace-fraud-result-local
          destination: mp-fraud-validation-result
        checkFraud-out-0:
          binder: kafka-mp
          contentType: application/json
          group: marketplace-fraud-local
          destination: mp-fraud-validation
        verificationResult-in-0:
          binder: kafka-mp
          contentType: application/json
          group: marketplace-dvs-local
          destination: mp-order-dvs
        prePurchaseResult-in-0:
          binder: kafka-mp
          contentType: application/json
          group: mp-pre-purchase-local
          destination: mp-pre-purchase
        prePurchase-out-0:
          binder: kafka-mp
          contentType: application/json
          destination: mp-pre-purchase

umico:
  api-key: 978f22df-62cb-4894-9811-ea26212c0b38

client:
  ete:
    url: http://presrsws.kapitalcard.az
  umico:
    url: https://broker-stage.umico.az/api/v2
  adp-atlas:
    url: https://pre.adp-atlas.kapitalbank.az/api/v1
  adp-optimus:
    url: https://pre.adp-optimus.kapitalbank.az/api/v1
  adp-dvs:
    url: https://pre.adp-dvs.kapitalbank.az/v1
  externalinteg:
    url: http://pre.externalinteg.kapitalbank.az/api
  ms-otp:
    url: https://pre.ms-otp.kapitalbank.az/v1
  loan:
    url: https://dev.ms-loan.kapitalbank.az/v1
  adp-common:
    url: https://pre.adp-common.kapitalbank.az/api/v1
feign:
  httpclient:
    disable-ssl-validation: true
    enabled: false
  okhttp:
    enabled: true

server:
  port: 8080

commission:
  values:
    1: 2.50
    2: 3.50
    3: 5.00
    6: 7.50
    12: 13.50
    18: 18.50
    24: 23.50

sms:
  text:
    preapprove: Kredit muracietiniz qeyde alinib. Uz tanima ile davam edin.
    complete-scoring: Kredit sorgunuz tesdiqlendi.Kredit xetti %s manat.
    pre-purchase: %s manat bloklanib.
    pending: Bank tezlikle sizinle elaqe saxlayacaq.