descriptions:
  values:
    preapprove: Kredit muracietiniz qeyde alinib. Uz tanima ile davam edin.
    scoringCompleted: Kredit sorgunuz tesdiqlendi.
    pre-purchase: manat bloklanib.
    pending: Bank tezlikle sizinle elaqe saxlayacaq.