sms:
  text:
    preapprove: Kredit muracietiniz qeyde alinib. Uz tanima ile davam edin.
    complete-scoring: Kredit sorgunuz tesdiqlendi.Kredit xetti %s manat.
    pre-purchase: %s manat bloklanib.
    pending: Bank tezlikle sizinle elaqe saxlayacaq.