spring:
  application:
    name: springboot-template-ms
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  cloud:
    consul:
      host: consul.kapitalbank.az
      port: 8500
      config:
        enabled: true
        fail-fast: true
        format: yaml
        profile-separator: '-'
        prefix: config/${K8S_NS:birbank}/${spring.application.name}
        data-key: data
    vault:
      host: vault.kapitalbank.az
      port: 8200
      fail-fast: false
      scheme: http
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: ${K8S_NS:birbank}/${spring.application.name}
        application-name: ${K8S_NS:birbank}/${spring.application.name}
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
  config:
    import:
      - "vault:/secret/${K8S_NS:birbank}/${spring.application.name}/${spring.profiles.active}"
      - "consul:"