package az.kapitalbank.marketplace.constant;

public enum OperationStatus {
    OPTIMUS_FAIL_START_SCORING,
    OPTIMUS_FAIL_CREATE_SCORING,
    OPTIMUS_FAIL_COMPLETE_SCORING,
    OPTIMUS_FAIL_GET_PROCESS,
    OPTIMUS_FAIL_BUSINESS_ERROR_OR_INCIDENT_HAPPENED,
    OPTIMUS_FAIL_GET_CARDID,
    DVS_URL_FAIL,
    OPTIMUS_NO_ENOUGH_AMOUNT
}
