package az.kapitalbank.marketplace.constant;

import lombok.Getter;

@Getter
public enum RejectedBusinessError {
    RULE_HAS_WRITTEN_OF_CREDIT,
    RULE_KB_HAS_ACTIVE_RESTRUCTURING_CREDIT,
    RULE_M_CATEGORY_NON_PENSIONER,
    RULE_NON_KB_HAS_ACTIVE_RESTRUCTURING_CREDIT,
    RULE_CUSTOMER_S_COMPANY_IS_BLACK_LIST,
    RULE_CUSTOMER_IS_POLITICAL_PERSON,
    RULE_CUSTOMER_COMPANY_DEGREE_IS_FOURTH,
    RULE_CUSTOMER_HAS_FIRST_GROUP_DISABILITY,
    RULE_CUSTOMER_INCOME_IS_NOT_EXIST,
    RULE_CUSTOMER_IS_ENTREPRENEUR_PERSON
}
