package az.kapitalbank.marketplace.constant;

import lombok.Getter;

@Getter
public enum RejectedBusinessError {
    RULE_HAS_WRITTEN_OF_CREDIT,
    RULE_KB_HAS_ACTIVE_RESTRUCTURING_CREDIT,
    RULE_M_CATEGORY_NON_PENSIONER,
    RULE_NON_KB_HAS_ACTIVE_RESTRUCTURING_CREDIT,
    RULE_CUSTOMER_IS_POLITICAL_PERSON,
    RULE_CUSTOMER_HAS_FIRST_GROUP_DISABILITY
}
