package az.kapitalbank.marketplace.constant;

public enum SendLeadReason {
    OPTIMUS_FAIL_START_SCORING,
    OPTIMUS_FAIL_CREATE_SCORING,
    OPTIMUS_FAIL_COMPLETE_SCORING,
    OPTIMUS_FAIL_GET_PROCESS,
    OPTIMUS_FAIL_BUSINESS_ERROR,
    OPTIMUS_FAIL_INCIDENT_HAPPENED,
    DVS_URL_FAIL,
    OPTIMUS_NO_ENOUGH_AMOUNT,
    FRAUD_LIST,
    NO_ACTION_DVS,
    SCORED_AMOUNT_IS_ZERO
}
