package az.kapitalbank.marketplace.client.atlas.model.response;

public enum Code {
    PURCHASE, PRE_PURCHASE, PRE_PURCHASE_COMPLETE, MAIL_PHONE_ORDER, MERCHANDISE_RETURN,
    CASH_ADVANCE, CARD_VERIFICATION, POS_BALANCE_INQUIRY, PURCHASE_WITH_CASH_BACK,
    PURCHASE_ADJUSTMENT, MERCHANDISE_RETURN_ADJUSTMENT, CASH_ADVANCE_ADJUSTMENT,
    PRE_PURCHASE_INCREMENT, PURCHASE_CANCELLATION, POS_MESSAGE_FINANCIAL_INSTITUTION, QUASI_CASH,
    POS_P2P_DEBIT, POS_P2P_CREDIT, POS_P2P_CALC_FEE, POS_P2P_PASS, POS_PIN_CHANGE, POS_DEPOSIT,
    POS_DEPOSIT_ADJUSTMENT, POS_TRANSFER_PASSWORD, CLOSE_DAY, POS_PREPAID_PASSWORD,
    POS_PREPAID_DEBIT, POS_PREPAID_CREDIT, POS_PAYMENT_PASSWORD, POS_ACCUMULATE_BONUS,
    POS_REDEEM_BONUS, POS_CASH_PAYMENT_PASSWORD, POS_CALC_FEE, ACCOUNT_DEBIT, ACCOUNT_CREDIT,
    MESSAGING_TRAFFIC
}
