package az.kapitalbank.marketplace.client.atlas.model.response;

public enum ResponseCode {
    UNKNOWN, APPROVAL, SYSTEM_ERROR, INVALID_REQUEST_FORMAT, CUSTOMER_CONFIRMATION_REQUIRED,
    DYNAMIC_PASSWORD_REQUIRED, PREPAID_CODE_NOT_FOUND, ACQUIRING_LIMIT_EXCEEDED, LOST_CARD,
    STOLEN_CARD, EXPIRED_CARD, CARD_NOT_FOUND, RESTRICTED_CARD, WEAK_PIN, INVALID_PIN_BLOCK_FORMAT,
    INVALID_CARD_PIN, PIN_TRIES_LIMIT_WAS_REACHED, PIN_TRIES_LIMIT_EXCEEDED,
    UNAUTHORIZED_CARD_USAGE, CONTACT_CARD_ISSUER, CARD_USAGE_LIMIT_EXCEEDED,
    CARD_WITHDRAWAL_LIMIT_WILL_BE_EXCEEDED, WITHDRAWAL_LIMIT_ALREADY_REACHED, DEPOSIT_LIMIT_REACHED,
    INSUFFICIENT_FUNDS, INVALID_CVV, INVALID_CVV2, INVALID_CAVV, PVV_VERIFICATION_FAILED,
    ACCOUNT_NOT_FOUND, ACCOUNT_ALREADY_EXISTS, UNABLE_ACCOUNT_CREDIT, INELIGIBLE_ACCOUNT,
    DUPLICATE_RATE, RATE_NOT_FOUND, INVALID_EXCHANGE_DATE, INVALID_CURRENCY_CODE,
    INVALID_CUSTOMER_ID, SUBSCRIBER_NOT_FOUND, SUBSCRIBER_BLOCKED, SUBSCRIBER_ALREADY_EXISTS,
    INVALID_DYNAMIC_PASSWORD, DYNAMIC_PASSWORD_LIFETIME_EXPIRED,
    DYNAMIC_PASSWORD_TRIES_LIMIT_EXCEEDED, INVALID_TRANSACTION, INVALID_TRANSACTION_RETAILER,
    TRANSACTION_LIMIT_EXCEEDED, DUPLICATE_TRANSACTION, INVALID_TRANSACTION_TERMINAL,
    INVALID_TRANSACTION_AMOUNT, INELIGIBLE_TRANSACTION, TRANSACTION_NOT_SUPPORTED,
    TRANSACTION_PARTIALLY_APPROVED, TRANSACTION_REVERSED, ONLY_PURCHASE_APPROVED,
    ORIGINAL_TRANSACTION_NOT_FOUND, TRANSACTION_EXTERNAL_DECLINE, STATEMENT_NOT_AVAILABLE,
    ROUTING_ERROR, AUTHORIZER_NOT_AVAILABLE, OPERATION_NOT_ALLOWED, CORRESPONDING_ACCOUNT_EXHAUSTED,
    INVALID_INSTITUTION_NAME, INVALID_CARD_PASSWORD, SUBSCRIPTION_ALREADY_EXIST, DUPLICATE_RECORD
}
