package az.kapitalbank.marketplace.constants;

public enum ProcessType {
    PRE_APPROVE_START,
    PRE_APPROVE_CREATE,
    COMPLETE,

    SCORING_START,
    SCORING_SUCCESS,
    SCORING_FAILURE,

    SCORING_CREATE_START,
    SCORING_CREATE_SUCCESS,

    RE_SCORING_START,
    RE_SCORING_SUCCESS,

    OPTIMUS_FAILURE,
    DEFAULT_SCORING
}